#!/bin/bash
#SBATCH -p LM
#SBATCH --mem=128GB
#SBATCH -t 120:00:00
#SBATCH --mail-type=ALL
#SBATCH --mail-user=markphuong@gmail.com

#echo commands to stdout

module load blat/v35
#move to working directory


#run python script
blat geographus.genome.v2.fixed.fa geographus.transcripts.clustered.fasta geographus.blatoutput.psl


