#!/bin/bash
#SBATCH -p LM
#SBATCH --mem=768GB
#SBATCH -t 24:00:00
#SBATCH --ntasks-per-node 16
#SBATCH --mail-type=ALL
#SBATCH --mail-user=markphuong@gmail.com

#echo commands to stdout

module load python/2.7.11_gcc


#move to working directory
cp *py $LOCAL
cp map* $LOCAL
cd $LOCAL

#run python script
python 2spadesWrapper_JAWAD.py --map mapfile0
